### ISSUE TITLE
Stability parameters not accessible

### ISSUE THREAD

**Issue by daniel-caichac-DHI** [pyCOARE/coare#20]
Hi, right under this line` stability_parameters` is missing
https://github.com/pyCOARE/coare/blob/9e52d86024573105585ed724d3170dcd72d4b2b8/pycoare/coare_35.py#L787

but I am not sure if this repo is still actively being developed? 
Thanks for the answer.

**Comment by daniel-caichac-DHI** [comment]
See #21 

tagging @andrew-s28 just in case :)

**Comment by andrew-s28** [comment]
Hey @daniel-caichac-DHI, sorry for the late reply!

This has been a bit of a personal side-project so far, so I wasn't exactly keeping up on the notifications. But I'm glad it's finding some use by others it seems, and thanks for making the issue.

Anyways, I am happy to keep this developed as best I can. I appreciate the PR and will get it merged ASAP.

**Comment by andrew-s28** [comment]
Addressed by #21

**Comment by daniel-caichac-DHI** [comment]
Hi @andrew-s28 
No sweat. Thanks for looking at this and merging quickly.
And thanks for developing this package in the first place! I was looking at the original `Coare` code vs this one, and even though they do the same (this one is based on the original), the code readability and architecture of your package is just far superior. You cannot imagine the frustrations I've had with the original Coare trying to access  some of the variables, which are just column numbers as in, `u star is column 47, and charnock coefficient is column 3`; it is too error-prone.
However with pycoare, is honestly a luxury to access variables in a OOP way such as `A.u_star`, or `A.charnock`.
And not to mention installation, `pip install pycoare` vs copy-paste some random files in some random folder and try to keep track of it :P
So please, keep up the good work, and I'd be happy to collaborate when I get the chance.
